# Generated by Django 2.2.6 on 2021-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon'),
        ),
    ]
