# Generated by Django 2.2.6 on 2021-08-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_shortlink_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='reception',
        ),
        migrations.AddField(
            model_name='stafftranslation',
            name='reception',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
