# Generated by Django 2.2.6 on 2021-08-20 14:59

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210811_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignRepresentativeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default=None, upload_to='icons/', verbose_name='icon')),
                ('file', models.FileField(upload_to='files/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Foreign Representative Items',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForeignRepresentativeLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Foreign Representative Links',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForeignRepresentativeLinksTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.ForeignRepresentativeLinks')),
            ],
            options={
                'verbose_name': 'Foreign Representative Links Translation',
                'db_table': 'blogs_foreignrepresentativelinks_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForeignRepresentativeItemsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.ForeignRepresentativeItems')),
            ],
            options={
                'verbose_name': 'Foreign Representative Items Translation',
                'db_table': 'blogs_foreignrepresentativeitems_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
