# Generated by Django 2.2.6 on 2021-08-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210820_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='_type',
            field=models.CharField(choices=[('directors', 'directors'), ('press', 'press'), ('other', 'other')], default='other', max_length=255),
        ),
    ]
