# Generated by Django 2.2.6 on 2021-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_staff__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualreception',
            name='region',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('kashkadarya', 'Kashkadarya'), ('samarkand', 'Samarkand'), ('sirdarya', 'Sirdarya'), ('surkhandarya', 'Surkhandarya'), ('tashkent', 'Tashkent'), ('tashkent_city', 'Tashkent city'), ('karakalpakstan', 'Karakalpakstan')], default='Tashkent', max_length=255),
        ),
    ]
