# Generated by Django 2.2.6 on 2021-08-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210826_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutranslation',
            name='link',
        ),
        migrations.AddField(
            model_name='foreighnadmin',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='foreighnadmin',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_item', to='blogs.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
