# Generated by Django 2.2.6 on 2021-09-06 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='virtualreception',
            old_name='full_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='AndijanNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='BukharaNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='FerganaNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='GulistonNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='JizzakhNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='KarakalpakstanNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='NamanganNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='NavoiyNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='QashqadaryoNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='SamarqandNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='SirdaryoNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='SurxondaryoNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='TashkentNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='TashkentRegionNumber',
        ),
        migrations.RemoveField(
            model_name='region',
            name='XorazmNumber',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Andijan',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Bukhara',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Fergana',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Guliston',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Jizzakh',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Karakalpakstan',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Namangan',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Navoiy',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Qashqadaryo',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Samarqand',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Sirdaryo',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Surxondaryo',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Tashkent',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='TashkentRegion',
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='Xorazm',
        ),
        migrations.RemoveField(
            model_name='virtualreception',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='virtualreception',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='virtualreception',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='companytypes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytypes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.GalleryCategory'),
        ),
        migrations.AddField(
            model_name='region',
            name='director_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/directors/'),
        ),
        migrations.AddField(
            model_name='region',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='region',
            name='path_directions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='regiontranslation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='regiontranslation',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Director Name'),
        ),
        migrations.AddField(
            model_name='regiontranslation',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Region Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.ProductCategory'),
        ),
        migrations.CreateModel(
            name='ProductCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.ProductCategory')),
            ],
            options={
                'verbose_name': 'product category Translation',
                'db_table': 'blogs_productcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
