# Generated by Django 2.2.6 on 2021-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210906_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='icon',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
