# Generated by Django 2.2.6 on 2021-09-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210906_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='icon',
            field=models.FileField(max_length=250, null=True, upload_to=''),
        ),
    ]
