# Generated by Django 2.2.6 on 2021-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210906_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitsadmin',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='benefitsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Benefit Translation'},
        ),
        migrations.AlterModelOptions(
            name='companytypes',
            options={'verbose_name': 'Company Type', 'verbose_name_plural': 'Company Types'},
        ),
        migrations.AlterModelOptions(
            name='companytypestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Company Type Translation'},
        ),
        migrations.AlterModelOptions(
            name='eventsadmin',
            options={'verbose_name': 'Events Admin', 'verbose_name_plural': 'Events Admin'},
        ),
        migrations.AlterModelOptions(
            name='eventsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Events Admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportersadmin',
            options={'verbose_name': 'Exporter', 'verbose_name_plural': 'Exporters'},
        ),
        migrations.AlterModelOptions(
            name='exportersadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Exporter Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportimplementationadmin',
            options={'verbose_name': 'Export Implementation', 'verbose_name_plural': 'Export Implementations'},
        ),
        migrations.AlterModelOptions(
            name='exportlawadmin',
            options={'verbose_name': 'Export Law', 'verbose_name_plural': 'Export Laws'},
        ),
        migrations.AlterModelOptions(
            name='exportpotentialadmin',
            options={'verbose_name': 'Export Potential', 'verbose_name_plural': 'Export Potentials'},
        ),
        migrations.AlterModelOptions(
            name='foreighnadmin',
            options={'verbose_name': 'Foreighn Representation', 'verbose_name_plural': 'Foreighn Representations'},
        ),
        migrations.AlterModelOptions(
            name='foreignrepresentativeitems',
            options={'verbose_name': 'Foreign Representative Item', 'verbose_name_plural': 'Foreign Representative Items'},
        ),
        migrations.AlterModelOptions(
            name='foreignrepresentativeitemstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Foreign Representative Item Translation'},
        ),
        migrations.AlterModelOptions(
            name='foreignrepresentativelinks',
            options={'verbose_name': 'Foreign Representative Link', 'verbose_name_plural': 'Foreign Representative Links'},
        ),
        migrations.AlterModelOptions(
            name='foreignrepresentativelinkstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Foreign Representative Link Translation'},
        ),
        migrations.AlterModelOptions(
            name='historyadmin',
            options={'verbose_name': 'History of Organization', 'verbose_name_plural': 'History of Organization'},
        ),
        migrations.AlterModelOptions(
            name='howtojoin',
            options={'verbose_name': 'How to join', 'verbose_name_plural': 'How to join'},
        ),
        migrations.AlterModelOptions(
            name='investmentpotentialadmin',
            options={'verbose_name': 'Investment potential', 'verbose_name_plural': 'Investment potentials'},
        ),
        migrations.AlterModelOptions(
            name='investorsadmin',
            options={'verbose_name': 'Investor', 'verbose_name_plural': 'Investors'},
        ),
        migrations.AlterModelOptions(
            name='investorsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Investor Translation'},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategies',
            options={'verbose_name': 'Market entry strategy', 'verbose_name_plural': 'Market entry strategies'},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategiestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Market entry strategy Translation'},
        ),
        migrations.AlterModelOptions(
            name='menucompanys',
            options={'verbose_name': 'Menu Company', 'verbose_name_plural': 'Menu Companys'},
        ),
        migrations.AlterModelOptions(
            name='menucompanystranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Menu Company Translation'},
        ),
        migrations.AlterModelOptions(
            name='menuoverlay',
            options={'verbose_name': 'Menu Overlay', 'verbose_name_plural': 'Menu Overlays'},
        ),
        migrations.AlterModelOptions(
            name='moscowadmin',
            options={'verbose_name': 'Moscow', 'verbose_name_plural': 'Moscow'},
        ),
        migrations.AlterModelOptions(
            name='presentationsadmin',
            options={'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
        migrations.AlterModelOptions(
            name='presentationsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Presentation Translation'},
        ),
        migrations.AlterModelOptions(
            name='pressreleasesadmin',
            options={'verbose_name': 'Press Release', 'verbose_name_plural': 'Press Releases'},
        ),
        migrations.AlterModelOptions(
            name='pressreleasesadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Press Release Translation'},
        ),
        migrations.AlterModelOptions(
            name='pressserviceadmin',
            options={'verbose_name': 'Press service', 'verbose_name_plural': 'Press services'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Product Category Translation'},
        ),
        migrations.AlterModelOptions(
            name='publicationsadmin',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='publicationsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Publication Translation'},
        ),
        migrations.AlterModelOptions(
            name='structureadmin',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterModelOptions(
            name='subsidaries2admin',
            options={'verbose_name': 'Subsidary 2', 'verbose_name_plural': 'Subsidaries 2'},
        ),
        migrations.AlterModelOptions(
            name='subsidaries2admintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Subsidary 2 Translation'},
        ),
        migrations.AlterModelOptions(
            name='subsidariesadmin',
            options={'verbose_name': 'Subsidary', 'verbose_name_plural': 'Subsidaries'},
        ),
        migrations.AlterModelOptions(
            name='subsidariesadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Subsidary Translation'},
        ),
        migrations.AlterModelOptions(
            name='territorialadmin',
            options={'verbose_name': 'Territorial Administration', 'verbose_name_plural': 'Territorial Administration'},
        ),
        migrations.AlterModelOptions(
            name='youthpolicyadmin',
            options={'verbose_name': 'Youth Policy', 'verbose_name_plural': 'Youth Policies'},
        ),
    ]
