# Generated by Django 2.2.6 on 2021-09-08 19:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210907_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytypestranslation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Full text'),
        ),
    ]
